# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: UTF8
  host: localhost
  pool: 5
  username: ubuntu
  password: password

development:
  <<: *default
  database: commuters_app_development

test:
  <<: *default
  database: commuters_app_test

production:
  <<: *default
  database: commuters_app_production
